package deoca.hhv.transport.trip.entity;

import deoca.hhv.transport.driver.entity.Driver;
import deoca.hhv.transport.fuel.entity.FuelIssue;
import deoca.hhv.transport.fuelnorm.entity.Purpose;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;

@Entity
@Setter
@Getter
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "trip_log_detail")
@Builder
public class TripLogDetail {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    @ManyToOne
    @JoinColumn(name = "trip_log_id")
    private TripLog tripLog;

    @ManyToOne
    @JoinColumn(name = "driver_id")
    private Driver driver;

    private LocalDate workDate;

    private String workContent;

    private Double startKm;

    private Double endKm;

    @Column(name = "working_hour")
    private Double workingHour;

    @Column(name = "idle_hour")
    private Double idleHour;

    @Column(name = "fuel_received")
    private Double fuelReceived;

    private String note;

    @Column(name = "fuel_consumed")
    private Double fuelConsumed;

    @Column(name = "distance")
    private Double distance;

    @ManyToOne
    @JoinColumn(
            name = "fuel_issue_id"
    )
    private FuelIssue fuelIssue;

    @ManyToOne
    @JoinColumn(name = "purpose_id")
    private Purpose purpose;

    private Boolean autoGenerated;
}
