package deoca.hhv.transport.trip.dto.response;

import lombok.*;

import java.time.LocalDate;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TripLogDetailResponse {

    private String id;

    private String tripLogId;

    private String driverId;

    private String driverName;

    private LocalDate workDate;

    private String workContent;

    private Double startKm;

    private Double endKm;

    private Double distance;

    private Double workingHour;

    private Double idleHour;

    private Double fuelReceived;

    private String note;

    private Boolean autoGenerated;

}
