package deoca.hhv.transport.trip.dto.response;

import lombok.Builder;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDate;

@Setter
@Getter
@Builder
public class TripLogDetailResponse {

    private String id;

    private LocalDate workDate;

    private String workContent;

    private Double startKm;

    private Double endKm;

    private Double distance;

    private Double workingHour;

    private Double idleHour;

    private Double fuelReceived;

    private String note;

    private Boolean autoGenerated;

}
