package deoca.hhv.transport.trip.dto.response;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.util.List;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TripDetailLineResponse {

    private String id;

    private String driverId;

    private String driverName;

    private LocalDate workDate;

    private String workContent;

    private Double startKm;

    private Double endKm;

    private Double distance;

    private Double workingHour;

    private Double idleHour;

    private Double fuelReceived;

    private Double fuelConsumed;

    private String note;

    private Boolean autoGenerated;

    private String fuelIssueId;
}
