package deoca.hhv.transport.trip.service.impl;

import deoca.hhv.transport.driver.entity.Driver;
import deoca.hhv.transport.driver.repository.DriverRepository;
import deoca.hhv.transport.exception.AppException;
import deoca.hhv.transport.exception.ErrorCode;
import deoca.hhv.transport.trip.dto.request.TripLogDetailCreateRequest;
import deoca.hhv.transport.trip.dto.request.TripLogDetailUpdateRequest;
import deoca.hhv.transport.trip.dto.response.TripDetailLineResponse;
import deoca.hhv.transport.trip.dto.response.TripLogDetailDeleteResponse;
import deoca.hhv.transport.trip.dto.response.TripLogDetailResponse;
import deoca.hhv.transport.trip.entity.TripLog;
import deoca.hhv.transport.trip.entity.TripLogDetail;
import deoca.hhv.transport.trip.enums.TripStatus;
import deoca.hhv.transport.trip.repository.TripLogDetailRepository;
import deoca.hhv.transport.trip.repository.TripLogRepository;
import deoca.hhv.transport.trip.service.TripLogDetailService;
import deoca.hhv.transport.trip.validator.TripLogDetailValidator;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import org.modelmapper.ModelMapper;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

@Service
@RequiredArgsConstructor
@Transactional
public class TripLogDetailServiceImpl
            implements TripLogDetailService {

    private final TripLogRepository tripLogRepository;

    private final TripLogDetailRepository tripLogDetailRepository;

    private final DriverRepository driverRepository;

    private final TripLogDetailValidator validator;

    private final ModelMapper mapper;

    @Override
    public TripLogDetailResponse createDetail(
            String tripId,
            TripLogDetailCreateRequest request) {

        TripLog tripLog =
                tripLogRepository.findById(tripId)
                        .orElseThrow(
                                () -> new AppException(
                                        ErrorCode.TRIP_NOT_FOUND
                                )
                        );

        validator.validateTripEditable(
                tripLog
        );

        validator.validateWorkDate(
                tripLog,
                request.getWorkDate()
        );

        validator.validateKm(
                request.getStartKm(),
                request.getEndKm()
        );

        validator.validateWorkingHour(
                request.getWorkingHour()
        );

        validator.validateIdleHour(
                request.getIdleHour()
        );

        Driver driver =
                driverRepository.findById(
                                request.getDriverId()
                        )
                        .orElseThrow(
                                () -> new AppException(
                                        ErrorCode.DRIVER_NOT_FOUND
                                )
                        );

        Double distance = 0D;

        if(request.getStartKm() != null){

            distance =
                    request.getEndKm()
                            - request.getStartKm();
        }

        TripLogDetail detail =
                TripLogDetail.builder()
                        .id(UUID.randomUUID().toString())
                        .deleted(false)
                        .tripLog(tripLog)
                        .driver(driver)
                        .workDate(
                                request.getWorkDate()
                        )
                        .workContent(
                                request.getWorkContent()
                        )
                        .startKm(
                                request.getStartKm()
                        )
                        .endKm(
                                request.getEndKm()
                        )
                        .distance(
                                distance
                        )
                        .workingHour(
                                request.getWorkingHour()
                        )
                        .idleHour(
                                request.getIdleHour()
                        )
                        .fuelReceived(
                                request.getFuelReceived()
                        )
                        .note(
                                request.getNote()
                        )
                        .autoGenerated(false)
                        .build();

        detail =
                tripLogDetailRepository.save(
                        detail
                );

        recalculateTrip(
                tripLog
        );

        return TripLogDetailResponse.builder()
                .id(detail.getId())
                .tripLogId(tripLog.getId())
                .driverId(driver.getId())
                .driverName(driver.getFullName())
                .workDate(detail.getWorkDate())
                .workContent(detail.getWorkContent())
                .startKm(detail.getStartKm())
                .endKm(detail.getEndKm())
                .distance(detail.getDistance())
                .workingHour(detail.getWorkingHour())
                .idleHour(detail.getIdleHour())
                .fuelReceived(detail.getFuelReceived())
                .note(detail.getNote())
                .autoGenerated(
                        detail.getAutoGenerated()
                )
                .build();
    }

    @Override
    @Transactional
    public TripLogDetailResponse getDetails(
            String tripId
    ) {
        TripLog tripLog =
                tripLogRepository
                        .findById(tripId)
                        .orElseThrow(
                                () ->
                                        new AppException(
                                                ErrorCode.TRIP_NOT_FOUND
                                        )
                        );

        List<TripLogDetail> details =
                tripLogDetailRepository
                        .findByTripLogIdOrderByWorkDateAsc(
                                tripId
                        );

        List<TripDetailLineResponse> lines =
                details.stream()
                        .map(this::mapToLineResponse)
                        .toList();

        return TripLogDetailResponse
                .builder()
                .tripLogId(
                        tripLog.getId()
                )
                .details(
                        lines
                )
                .build();
    }

    @Override
    public TripLogDetailResponse updateDetail(
            String detailId,
            TripLogDetailUpdateRequest request
    ) {
        TripLogDetail detail =
                tripLogDetailRepository
                        .findById(detailId)
                        .orElseThrow(
                                () ->
                                        new AppException(
                                                ErrorCode.TRIP_DETAIL_NOT_FOUND
                                        )
                        );

        TripLog tripLog =
                detail.getTripLog();

    /*
        Không cho sửa khi đã chốt
     */
        if (
                tripLog.getStatus()
                        ==
                        TripStatus.CLOSED
        ) {

            throw new AppException(
                    ErrorCode.TRIP_CLOSED
            );
        }

    /*
        Kiểm tra tài xế
     */
        Driver driver =
                driverRepository
                        .findById(
                                request.getDriverId()
                        )
                        .orElseThrow(
                                () ->
                                        new AppException(
                                                ErrorCode.DRIVER_NOT_FOUND
                                        )
                        );

    /*
        Không cho nhập ngoài tháng
     */
        if (
                request.getWorkDate().getMonthValue()
                        !=
                        tripLog.getMonth()
        ) {

            throw new AppException(
                    ErrorCode.INVALID_WORK_DATE
            );
        }

        if (
                request.getWorkDate().getYear()
                        !=
                        tripLog.getYear()
        ) {

            throw new AppException(
                    ErrorCode.INVALID_WORK_DATE
            );
        }

    /*
        Trùng ngày
     */
//        boolean existed =
//                tripLogDetailRepository
//                        .existsByTripLogIdAndWorkDateAndIdNot(
//                                tripLog.getId(),
//                                request.getWorkDate(),
//                                detailId
//                        );
//
//        if (existed) {
//
//            throw new AppException(
//                    ErrorCode.DUPLICATE_WORK_DATE
//            );
//        }

    /*
        Km cuối >= Km đầu
     */
        if (
                request.getStartKm() != null
                        &&
                        request.getEndKm()
                                <
                                request.getStartKm()
        ) {

            throw new AppException(
                    ErrorCode.INVALID_KM
            );
        }

    /*
        Giờ hoạt động
     */
        if (
                request.getWorkingHour() != null
                        &&
                        request.getWorkingHour() < 0
        ) {

            throw new AppException(
                    ErrorCode.INVALID_WORKING_HOUR
            );
        }

    /*
        Giờ nổ máy
     */
        if (
                request.getIdleHour() != null
                        &&
                        request.getIdleHour() < 0
        ) {

            throw new AppException(
                    ErrorCode.INVALID_IDLE_HOUR
            );
        }

        detail.setWorkDate(
                request.getWorkDate()
        );

        detail.setDriver(
                driver
        );

        detail.setWorkContent(
                request.getWorkContent()
        );

        detail.setStartKm(
                request.getStartKm()
        );

        detail.setEndKm(
                request.getEndKm()
        );

        detail.setWorkingHour(
                request.getWorkingHour()
        );

        detail.setIdleHour(
                request.getIdleHour()
        );

        detail.setFuelReceived(
                request.getFuelReceived()
        );

        detail.setNote(
                request.getNote()
        );

    /*
        Tính khoảng cách
     */
        if (
                request.getStartKm() != null
                        &&
                        request.getEndKm() != null
        ) {

            detail.setDistance(
                    request.getEndKm()
                            -
                            request.getStartKm()
            );
        }

        tripLogDetailRepository.save(
                detail
        );

        return mapToResponse(
                detail
        );
    }

    @Override
    @Transactional
    public TripLogDetailDeleteResponse deleteDetail(
            String detailId
    ) {

//        System.out.println("DELETE ID = " + detailId);
//
//        Optional<TripLogDetail> test =
//                tripLogDetailRepository.findById(detailId);
//
//        System.out.println(
//                "FOUND = " + test.isPresent()
//        );

        TripLogDetail detail =
                tripLogDetailRepository
                        .findByIdAndDeletedFalse(
                                detailId
                        )
                        .orElseThrow(
                                () ->
                                        new AppException(
                                                ErrorCode.TRIP_DETAIL_NOT_FOUND
                                        )
                        );

        TripLog tripLog =
                detail.getTripLog();

    /*
        Không cho xóa khi đã chốt
     */
        if (
                tripLog.getStatus()
                        ==
                        TripStatus.CLOSED
        ) {

            throw new AppException(
                    ErrorCode.TRIP_CLOSED
            );
        }

    /*
        Không cho xóa dòng tự sinh
     */
        if (
                Boolean.TRUE.equals(
                        detail.getAutoGenerated()
                )
        ) {

            throw new AppException(
                    ErrorCode.AUTO_GENERATED_DETAIL_CANNOT_DELETE
            );
        }

        detail.setDeleted(
                true
        );

        detail.setDeletedAt(
                LocalDateTime.now()
        );

    /*
       Sau này thay bằng user login
     */
        detail.setDeletedBy(
                "SYSTEM"
        );

        tripLogDetailRepository.save(
                detail
        );

        return TripLogDetailDeleteResponse
                .builder()
                .detailId(
                        detail.getId()
                )
                .tripId(
                        tripLog.getId()
                )
                .message(
                        "Xóa dòng nhật trình thành công"
                )
                .deletedAt(
                        detail.getDeletedAt()
                )
                .build();
    }

    private TripLogDetailResponse mapToResponse(
            TripLogDetail detail
    ) {

        return TripLogDetailResponse
                .builder()
                .id(
                        detail.getId()
                )
                .tripLogId(
                        detail.getTripLog().getId()
                )
                .driverId(
                        detail.getDriver().getId()
                )
                .driverName(
                        detail.getDriver().getFullName()
                )
                .workDate(
                        detail.getWorkDate()
                )
                .workContent(
                        detail.getWorkContent()
                )
                .startKm(
                        detail.getStartKm()
                )
                .endKm(
                        detail.getEndKm()
                )
                .distance(
                        detail.getDistance()
                )
                .workingHour(
                        detail.getWorkingHour()
                )
                .idleHour(
                        detail.getIdleHour()
                )
                .fuelReceived(
                        detail.getFuelReceived()
                )
                .note(
                        detail.getNote()
                )
                .autoGenerated(
                        detail.getAutoGenerated()
                )
                .build();
    }

    private TripDetailLineResponse mapToLineResponse(
            TripLogDetail detail
    ) {

        return TripDetailLineResponse
                .builder()
                .id(
                        detail.getId()
                )
                .workDate(
                        detail.getWorkDate()
                )
                .driverId(
                        detail.getDriver().getId()
                )
                .driverName(
                        detail.getDriver().getFullName()
                )
                .workContent(
                        detail.getWorkContent()
                )
                .startKm(
                        detail.getStartKm()
                )
                .endKm(
                        detail.getEndKm()
                )
                .distance(
                        detail.getDistance()
                )
                .workingHour(
                        detail.getWorkingHour()
                )
                .idleHour(
                        detail.getIdleHour()
                )
                .fuelReceived(
                        detail.getFuelReceived()
                )
                .note(
                        detail.getNote()
                )
                .autoGenerated(
                        detail.getAutoGenerated()
                )
                .build();
    }

//    Hàm tính lại trip

    private void recalculateTrip(
            TripLog tripLog
    ){

        List<TripLogDetail> details =
                tripLogDetailRepository
                        .findByTripLogIdOrderByWorkDateAsc(
                                tripLog.getId()
                        );

        double totalKm = 0D;

        double totalWorkingHour = 0D;

        double totalIdleHour = 0D;

        double totalFuelReceived = 0D;

        for(TripLogDetail detail : details){

            totalKm +=
                    detail.getDistance() == null
                            ? 0D
                            : detail.getDistance();

            totalWorkingHour +=
                    detail.getWorkingHour() == null
                            ? 0D
                            : detail.getWorkingHour();

            totalIdleHour +=
                    detail.getIdleHour() == null
                            ? 0D
                            : detail.getIdleHour();

            totalFuelReceived +=
                    detail.getFuelReceived() == null
                            ? 0D
                            : detail.getFuelReceived();
        }

        tripLog.setTotalKm(
                totalKm
        );

        tripLog.setTotalWorkingHour(
                totalWorkingHour
        );

        tripLog.setTotalIdleHour(
                totalIdleHour
        );

        tripLog.setTotalFuelReceived(
                totalFuelReceived
        );

        tripLogRepository.save(
                tripLog
        );
    }

}

