package deoca.hhv.transport.trip.service.impl;

import deoca.hhv.transport.driver.entity.Driver;
import deoca.hhv.transport.driver.repository.DriverRepository;
import deoca.hhv.transport.exception.AppException;
import deoca.hhv.transport.exception.ErrorCode;
import deoca.hhv.transport.trip.dto.request.TripLogDetailCreateRequest;
import deoca.hhv.transport.trip.dto.response.TripDetailLineResponse;
import deoca.hhv.transport.trip.dto.response.TripLogDetailResponse;
import deoca.hhv.transport.trip.entity.TripLog;
import deoca.hhv.transport.trip.entity.TripLogDetail;
import deoca.hhv.transport.trip.repository.TripLogDetailRepository;
import deoca.hhv.transport.trip.repository.TripLogRepository;
import deoca.hhv.transport.trip.service.TripLogDetailService;
import deoca.hhv.transport.trip.validator.TripLogDetailValidator;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import org.modelmapper.ModelMapper;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
@RequiredArgsConstructor
@Transactional
public class TripLogDetailServiceImpl
            implements TripLogDetailService {

    private final TripLogRepository tripLogRepository;

    private final TripLogDetailRepository tripLogDetailRepository;

    private final DriverRepository driverRepository;

    private final TripLogDetailValidator validator;

    private final ModelMapper mapper;

    @Override
    public TripLogDetailResponse createDetail(
            String tripId,
            TripLogDetailCreateRequest request) {

        TripLog tripLog =
                tripLogRepository.findById(tripId)
                        .orElseThrow(
                                () -> new AppException(
                                        ErrorCode.TRIP_NOT_FOUND
                                )
                        );

        validator.validateTripEditable(
                tripLog
        );

        validator.validateWorkDate(
                tripLog,
                request.getWorkDate()
        );

        validator.validateKm(
                request.getStartKm(),
                request.getEndKm()
        );

        validator.validateWorkingHour(
                request.getWorkingHour()
        );

        validator.validateIdleHour(
                request.getIdleHour()
        );

        Driver driver =
                driverRepository.findById(
                                request.getDriverId()
                        )
                        .orElseThrow(
                                () -> new AppException(
                                        ErrorCode.DRIVER_NOT_FOUND
                                )
                        );

        Double distance = 0D;

        if(request.getStartKm() != null){

            distance =
                    request.getEndKm()
                            - request.getStartKm();
        }

        TripLogDetail detail =
                TripLogDetail.builder()
                        .tripLog(tripLog)
                        .driver(driver)
                        .workDate(
                                request.getWorkDate()
                        )
                        .workContent(
                                request.getWorkContent()
                        )
                        .startKm(
                                request.getStartKm()
                        )
                        .endKm(
                                request.getEndKm()
                        )
                        .distance(
                                distance
                        )
                        .workingHour(
                                request.getWorkingHour()
                        )
                        .idleHour(
                                request.getIdleHour()
                        )
                        .fuelReceived(
                                request.getFuelReceived()
                        )
                        .note(
                                request.getNote()
                        )
                        .autoGenerated(false)
                        .build();

        detail =
                tripLogDetailRepository.save(
                        detail
                );

        recalculateTrip(
                tripLog
        );

        return TripLogDetailResponse.builder()
                .id(detail.getId())
                .tripLogId(tripLog.getId())
                .driverId(driver.getId())
                .driverName(driver.getFullName())
                .workDate(detail.getWorkDate())
                .workContent(detail.getWorkContent())
                .startKm(detail.getStartKm())
                .endKm(detail.getEndKm())
                .distance(detail.getDistance())
                .workingHour(detail.getWorkingHour())
                .idleHour(detail.getIdleHour())
                .fuelReceived(detail.getFuelReceived())
                .note(detail.getNote())
                .autoGenerated(
                        detail.getAutoGenerated()
                )
                .build();
    }

    @Override
    @Transactional
    public TripLogDetailResponse getDetails(
            String tripId
    ) {
        TripLog tripLog =
                tripLogRepository
                        .findById(tripId)
                        .orElseThrow(
                                () ->
                                        new AppException(
                                                ErrorCode.TRIP_NOT_FOUND
                                        )
                        );

        List<TripLogDetail> details =
                tripLogDetailRepository
                        .findByTripLogIdOrderByWorkDateAsc(
                                tripId
                        );

        List<TripDetailLineResponse> lines =
                details.stream()
                        .map(this::mapToLineResponse)
                        .toList();

        return TripLogDetailResponse
                .builder()
                .tripLogId(
                        tripLog.getId()
                )
                .details(
                        lines
                )
                .build();
    }

    private TripDetailLineResponse mapToLineResponse(
            TripLogDetail detail
    ) {

        return TripDetailLineResponse
                .builder()
                .id(
                        detail.getId()
                )
                .workDate(
                        detail.getWorkDate()
                )
                .driverId(
                        detail.getDriver().getId()
                )
                .driverName(
                        detail.getDriver().getFullName()
                )
                .workContent(
                        detail.getWorkContent()
                )
                .startKm(
                        detail.getStartKm()
                )
                .endKm(
                        detail.getEndKm()
                )
                .distance(
                        detail.getDistance()
                )
                .workingHour(
                        detail.getWorkingHour()
                )
                .idleHour(
                        detail.getIdleHour()
                )
                .fuelReceived(
                        detail.getFuelReceived()
                )
                .note(
                        detail.getNote()
                )
                .autoGenerated(
                        detail.getAutoGenerated()
                )
                .build();
    }

//    Hàm tính lại trip

    private void recalculateTrip(
            TripLog tripLog
    ){

        List<TripLogDetail> details =
                tripLogDetailRepository
                        .findByTripLogIdOrderByWorkDateAsc(
                                tripLog.getId()
                        );

        double totalKm = 0D;

        double totalWorkingHour = 0D;

        double totalIdleHour = 0D;

        double totalFuelReceived = 0D;

        for(TripLogDetail detail : details){

            totalKm +=
                    detail.getDistance() == null
                            ? 0D
                            : detail.getDistance();

            totalWorkingHour +=
                    detail.getWorkingHour() == null
                            ? 0D
                            : detail.getWorkingHour();

            totalIdleHour +=
                    detail.getIdleHour() == null
                            ? 0D
                            : detail.getIdleHour();

            totalFuelReceived +=
                    detail.getFuelReceived() == null
                            ? 0D
                            : detail.getFuelReceived();
        }

        tripLog.setTotalKm(
                totalKm
        );

        tripLog.setTotalWorkingHour(
                totalWorkingHour
        );

        tripLog.setTotalIdleHour(
                totalIdleHour
        );

        tripLog.setTotalFuelReceived(
                totalFuelReceived
        );

        tripLogRepository.save(
                tripLog
        );
    }
}

