package deoca.hhv.transport.trip.service.impl;

import deoca.hhv.transport.exception.AppException;
import deoca.hhv.transport.exception.ErrorCode;
import deoca.hhv.transport.trip.dto.request.TripLogDetailCreateRequest;
import deoca.hhv.transport.trip.dto.response.TripLogDetailResponse;
import deoca.hhv.transport.trip.entity.TripLog;
import deoca.hhv.transport.trip.entity.TripLogDetail;
import deoca.hhv.transport.trip.repository.TripLogDetailRepository;
import deoca.hhv.transport.trip.repository.TripLogRepository;
import deoca.hhv.transport.trip.service.TripLogDetailService;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import org.modelmapper.ModelMapper;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor
@Transactional
public class TripLogDetailServiceImpl
            implements TripLogDetailService {

    private final TripLogRepository tripLogRepository;

    private final TripLogDetailRepository tripLogDetailRepository;

    private final ModelMapper mapper;

    @Override
    public TripLogDetailResponse create(
            String tripId,
            TripLogDetailCreateRequest request) {

        TripLog tripLog =
                tripLogRepository.findById(tripId)
                        .orElseThrow(
                                () -> new AppException(
                                        ErrorCode.TRIP_NOT_FOUND
                                )
                        );

        if(Boolean.TRUE.equals(
                tripLog.getClosed()
        )){
            throw new AppException(
                    ErrorCode.TRIP_ALREADY_CLOSED
            );
        }

        TripLogDetail detail =
                new TripLogDetail();

        detail.setTripLog(tripLog);

        detail.setWorkDate(
                request.getWorkDate()
        );

        detail.setWorkContent(
                request.getWorkContent()
        );

        detail.setStartKm(
                request.getStartKm()
        );

        detail.setEndKm(
                request.getEndKm()
        );

        detail.setWorkingHour(
                request.getWorkingHour()
        );

        detail.setIdleHour(
                request.getIdleHour()
        );

        detail.setNote(
                request.getNote()
        );

        detail.setAutoGenerated(
                false
        );

        if(request.getStartKm() != null
                && request.getEndKm() != null){

            detail.setDistance(
                    request.getEndKm()
                            - request.getStartKm()
            );
        }

        detail =
                tripLogDetailRepository.save(
                        detail
                );

        return mapper.map(
                detail,
                TripLogDetailResponse.class
        );
    }
}
